#Gradle
org.gradle.jvmargs=-Xmx2048M -Dkotlin.daemon.jvm.options\="-Xmx2048M"
#org.gradle.warning.mode=none
#org.gradle.configuration-cache=true
#org.gradle.configuration-cache.problems=warn

#Kotlin
kotlin.code.style=official
#kotlin.native.ignoreDisabledTargets=true

#MPP
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.stability.nowarn=true
kotlin.js.generate.executable.default=false
kotlin.mpp.androidSourceSetLayoutVersion=2

#Android
android.compileSdk=36
android.targetSdk=36
android.minSdk=21
android.useAndroidX=true
