[versions]
korge = "7.0.0-SNAPSHOT"

# To check the version number of the latest Kotlin release, go to
# https://kotlinlang.org/docs/releases.html
kotlin = "2.3.21"

# Android target related
androidGradlePlugin = "9.2.1"
compileSdk = "36"
minSdk = "20"

# Versions of additions
kotlinxSerialization = "1.11.0"
kaml = "0.61.0"
fleks = "2.14"


[plugins]
korge = { id = "org.korge.engine", version.ref = "korge" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidGradlePlugin" }

# Additional plugins
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }


[libraries]
korge = { module = "org.korge.engine:korge", version.ref = "korge" }

# Additional libs
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }
fleks = { module = "io.github.quillraven.fleks:Fleks", version.ref = "fleks"}
