[plugins]
#korge = { id = "com.soywiz.korge", version = "3.4.0" }
#korge = { id = "com.soywiz.korge", version = "999.0.0.999" }
#korge = { id = "com.soywiz.korge", version = "4.0.0-alpha-6" }
korge = { id = "com.soywiz.korge", version = "4.0.0-beta" }
